version: "3.3"
services:
  elasticsearch:
    image: elasticsearch:8.2.2
    container_name: elasticsearch1
    networks:
      - elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:8.2.2
    container_name: kibana1
    networks:
      - elasticsearch
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

networks:
  elasticsearch:
    driver: bridge